Update push-code.yml

diff --git a/.github/workflows/push-code.yml b/.github/workflows/push-code.yml
--- a/.github/workflows/push-code.yml
+++ b/.github/workflows/push-code.yml
@@ -7,16 +7,16 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-latest # using ubuntu as the base image
+    runs-on: ubuntu-latest
 
     strategy:
       matrix:
-        python-version: [3.8, 3.9] # using 2 versions of python for better availability and to run on the base image 
+        python-version: [3.8,3.9]
 
     steps:
-    - uses: actions/checkout@v3 # @v3 is just the version of the plugin 
+    - uses: actions/checkout@v3
     - name: Set up Python
-      uses: actions/setup-python@v2 # @v2 is just the version of the plugin and the version of Python
+      uses: actions/setup-python@v2
       with:
         python-version: ${{ matrix.python-version }}
 
@@ -28,4 +28,7 @@ jobs:
     - name: Run tests
       run: |
         cd src
-        python -m pytest
+        if ! python -m pytest; then
+          echo "Tests failed. Exiting..."
+          exit 1
+        fi
